version: '3.8'

services:
  frontend:
    image: shaheen8954/chatapp-frontend:latest
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - chat-network
    environment:
      - BACKEND_URL=http://backend:5001

  backend:
    image: shaheen8954/chatapp-beckend:latest
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:admin@mongo:27017/chatApp?authSource=admin
      - PORT=5001
      - NODE_ENV=production
      - JWT_SECRET=b+2cKTuDiON3eA0MhUSb9AXTBT64WNiGGF0nVxGtaWw=
    networks:
      - chat-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=chatApp
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongo-data:
